---
title: "Comparação de parâmetros populacionais"
author: "William Peixoto"
date: "10 de junho de 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source("get_dv.R")
source("NormalCompara.R")
source("aux.R")

FN_PREFIXO = "detalhe_votacao_secao_"
FN_SUFIXO = "_DF.txt"
DATA_DIR = "./"
setwd("~/Nextcloud_CD/Cursos/Mestrado/MetodosInferenciais01/abstencao_eleitoral/dados")

# bld_filename <- function(DATA_DIR, ANO, FN_PREFIXO, FN_SUFIXO) {
bld_filename <- function(ANO) {
  paste0(DATA_DIR, "1998/", FN_PREFIXO, 1998, FN_SUFIXO)
}

#df98 = filtra_UF(get_dv(paste0(DATA_DIR, FN_PREFIXO, 1998, FN_SUFIXO), full = T), "DF")
df98 = get_dv(bld_filename(1998), full = T)
df98$SIGLA_UF <- "DF"  # Corrige erro nos dados
df02 = get_dv(paste0(DATA_DIR, "2002/", FN_PREFIXO, 2002, FN_SUFIXO), full = T)
df06 = get_dv(paste0(DATA_DIR, "2006/", FN_PREFIXO, 2006, FN_SUFIXO), full = T)
df10 = get_dv(paste0(DATA_DIR, "2010/", FN_PREFIXO, 2010, FN_SUFIXO), full = T)
df14 = get_dv(paste0(DATA_DIR, "2014/", FN_PREFIXO, 2014, FN_SUFIXO), full = T)

parametros = data.frame(
  ANO = rep(NA, 10),
  TURNO = rep(NA, 10),
  TAXA_MEDIA = rep(NA, 10),
  DP = rep(NA, 10)
)
```

```{r echo=F}
c = 1
#for (df in lapply(list(df98, df02, df06, df10, df14), FUN = filtra_DF)) {
for (df in list(df98, df02, df06, df10, df14)) {
  # turnos = c(df[df$NUM_TURNO == 1], df[df$NUM_TURNO == 2])
  #attach(df)
  # print(unique(ANO_ELEICAO))
  # print(unique(NUM_TURNO))
  # print(paste("df is " ,class(df)))
  turnos = split(df, df$NUM_TURNO)
  # detach(df)
  # print(paste("turnos is", class(turnos)))
  # print(class(turnos[[1]]))
  for (t in turnos) {
    NUM_TURNO = unique(t$NUM_TURNO)
    ANO_ELEICAO = unique(t$ANO_ELEICAO)
    parametros[c,] = list(
      ANO_ELEICAO,
      NUM_TURNO,
      fmtP(mean(t$TAXA_ABSTENCAO)),
      fmtP(sd(t$TAXA_ABSTENCAO))
    )
    c = c+1
  }
}

```

## Comparação dos parâmetros das taxas de abstenção

Levando em consideração todos os dados disponibilizados pelo TSe para as eleições de 1998, 2002, 2006, 2010 e 2014, temos o seguinte:

```{r echo=F}
library(knitr)
kable(parametros)
```

## Comparações dois a dois, primeiro turno

### 1998 x 2002

```{r echo=FALSE}
df98_t = split(df98, df98$NUM_TURNO)
df02_t = split(df02, df02$NUM_TURNO)
dnormC(df98_t[[1]]$TAXA_ABSTENCAO, df02_t[[1]]$TAXA_ABSTENCAO)
```

Again

```{r echo=F}
comparaTaxaA(df98, df02)
comparaTaxaA_EP(df98, df02)
```

### 2002 x 2006

```{r echo=F}
comparaTaxaA(df02, df06)
comparaTaxaA_EP(df02, df06)
```

### 2006 x 2010
```{r echo=F}
comparaTaxaA(df06, df10)

```

### 2010 x 2014
```{r echo=F}
comparaTaxaA(df10, df14)
```

## Idem, segundos turnos
### 1998 x 2002
```{r echo=F}
comparaTaxaA(df98, df02, turno = 2)
```

### 2002 x 2006
```{r echo=F}
# comparaTaxaA(df02, df06, turno = 2)
```

Não houve 2º turno em 2006

### 2006 x 2010
```{r echo=F}
# comparaTaxaA(df06, df10, turno = 2)
```

Não houve 2º turno em 2006

### 2002 x 2010
```{r echo=F}
comparaTaxaA(df02, df10, turno = 2)
```

### 2010 x 2014
```{r echo=F}
comparaTaxaA(df10, df14, turno = 2)
```

## Primeiros turnos x segundos turnos

### 1998
```{r echo=F}
#dnormC(df98[df98$NUM_TURNO == 1,]$TAXA_ABSTENCAO, df98[df98$NUM_TURNO == 2,]$TAXA_ABSTENCAO)
#df98_t = split(df98, df98$NUM_TURNO)
df98_t = list(df98[df98$NUM_TURNO == 1,]$TAXA_ABSTENCAO, df98[df98$NUM_TURNO == 2,]$TAXA_ABSTENCAO)
dnormC(df98_t[[1]], df98_t[[2]])
```

### 2002
```{r echo=F}
df_t = list(df02[df98$NUM_TURNO == 1,]$TAXA_ABSTENCAO, df98[df98$NUM_TURNO == 2,]$TAXA_ABSTENCAO)
dnormC(df_t[[1]], df_t[[2]])
```

### 2006

Não houve segundo turno para governador

### 2010
```{r echo=F}
df_t = list(df10[df98$NUM_TURNO == 1,]$TAXA_ABSTENCAO, df10[df98$NUM_TURNO == 2,]$TAXA_ABSTENCAO)
dnormC(df_t[[1]], df_t[[2]])
```

### 2014
```{r echo=F}
df_t = spliTurno(df14)
dnormC(df_t[[1]]$TAXA_ABSTENCAO, df_t[[2]]$TAXA_ABSTENCAO)
```
